### PR TITLE
Name and location suggestion

### PR DESCRIPTION
**Pull request by Malwine**
Suggestion to have name upcased and location displayed differently.
screen shot 2018-06-08 at 15 11 54

### CODE REVIEW

**Comment by daiyi** [comment]
Interesting!

I'd like to propose ISO 3166-1 alpha-2 for standardising country locations: https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

That way if we ever decide to do something cute (like parse country codes into emoji) it would be simple!

**Comment by Malwine** [comment]
@daiyi It looks like this now:
screen shot 2018-06-08 at 22 30 37

I think it would be cool to add a link to the twitter moment with cool sketchnotes below the bio as well.

**Comment by Malwine** [comment]
Oh but I just realize that we have to write `California` probably because `CA` is for Canada.

**Comment by Malwine** [comment]
Or just Oakland?

**Comment by daiyi** [comment]
How about `Oakland, CA • US`?

**Comment by Malwine** [comment]
I like that ! 😊

**Pull request merged**
